{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  labels:
    usage: ollama-storage-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  accessModes: {{ toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}
{{- end }}